name: Dispatch Scraper (self-hosted)

on:
  workflow_dispatch:

jobs:
  run:
    name: "Run price_scraper"
    runs-on: self-hosted
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4 # checkout the repository content to github runner

      # - name: Setup Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version-file: 'pyproject.toml'
      #     cache: 'pip'

      - name: Install price_scraper
        run: pip install .
          
      - name: Run price_scraper # run main.py
        env:
          LOG_LEVEL: 'INFO'
          INPUT_CONFIG_PATH: '/Users/andhrelja/Local/Private/price_scraper/config.json'
          DATA_DIR: '/Users/andhrelja/Local/Private/price_scraper/data'
        run: |
          python -m price_scraper --input-config-path ${INPUT_CONFIG_PATH}
          python reports/make.py
