name: Scheduled Scraper (ubuntu-latest)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # At 00:00

jobs:
  run:
    name: "Run price_scraper"
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4 # checkout the repository content to github runner

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version-file: 'pyproject.toml'
          cache: 'pip'
          
      - name: Install price_scraper
        run: pip install .
          
      - name: Run price_scraper # run main.py
        env:
          LOG_LEVEL: 'INFO'
          CONFIG_JSON_PATH: ${{ github.workspace }}/config.json
          REPOSITORY_IO_PATH: ${{ github.workspace }}/data
        run: python -m price_scraper --config-json-path $CONFIG_JSON_PATH
      
      - name: Generate report
        env:
          REPOSITORY_IO_PATH: ${{ github.workspace }}/data
        run: python reports/make.py
          
      - name: Commit data
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -a -m "chore(auto): update report" --allow-empty
          
      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
